name: lelewise_mobile_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  flutter_screenutil: 5.8.4
  flutter_time_picker_spinner: ^2.0.0
  iconsax: ^0.0.8
  flutter_hicons: ^0.1.0
  zoom_tap_animation: ^1.1.0
  iconly: ^1.0.1
  firebase_app_check: ^0.2.1+5
  cloud_firestore: ^4.13.2
  go_router: ^12.1.1
  firebase_database: ^10.3.5
  intl: ^0.18.1
  auto_route: ^7.8.4
  hive_generator: ^2.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  image_picker: ^1.0.4
  dotted_border: ^2.1.0
  dio: ^5.4.0
  permission_handler: ^11.1.0
  sn_progress_dialog: ^1.1.3
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  assets:
    - assets/
    - assets/icons/
    - - assets/image/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Light.ttf
        - asset: fonts/Satoshi-LightItalic.ttf
        - asset: fonts/Satoshi-Regular.ttf
        - asset: fonts/Satoshi-Italic.ttf
        - asset: fonts/Satoshi-Medium.ttf
        - asset: fonts/Satoshi-MediumItalic.ttf
        - asset: fonts/Satoshi-Bold.ttf
        - asset: fonts/Satoshi-BoldItalic.ttf
        - asset: fonts/Satoshi-Black.ttf
        - asset: fonts/Satoshi-BlackItalic.ttf

    - family: SFDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 800
    
  uses-material-design: true

