name: lelewise_mobile_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  flutter_screenutil: 5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.otf
          weight: 100
        - asset: fonts/Satoshi-MediumItalic.otf
          weight: 200
        - asset: fonts/Satoshi-Medium.otf
          weight: 300
        - asset: fonts/Satoshi-Light.otf
          weight: 400
        - asset: fonts/Satoshi-Italic.otf
          weight: 500
        - asset: fonts/Satoshi-BoldItalic.otf
          weight: 600
        - asset: fonts/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/Satoshi-Black.otf
          weight: 800

    - family: SFDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 800
    
  uses-material-design: true

