// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMK_7R7-8nlYjE7pdoPzqtmynSnBdsdc',
    appId: '1:11481576355:web:618f7b0615c37438be6016',
    messagingSenderId: '11481576355',
    projectId: 'lele-wise-5f987',
    authDomain: 'lele-wise-5f987.firebaseapp.com',
    databaseURL: 'https://lele-wise-5f987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lele-wise-5f987.appspot.com',
    measurementId: 'G-J179RQBV7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYHslDtCAwP55zIpFGBCqwDTHPWDwTok',
    appId: '1:11481576355:android:7155192f6fc30d89be6016',
    messagingSenderId: '11481576355',
    projectId: 'lele-wise-5f987',
    databaseURL: 'https://lele-wise-5f987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lele-wise-5f987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWu-Xm1UuAq2Wfh2VXanibObt5KFmzq6s',
    appId: '1:11481576355:ios:39985c43cc705f38be6016',
    messagingSenderId: '11481576355',
    projectId: 'lele-wise-5f987',
    databaseURL: 'https://lele-wise-5f987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lele-wise-5f987.appspot.com',
    iosBundleId: 'com.lelewise.lelewiseMobileApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWu-Xm1UuAq2Wfh2VXanibObt5KFmzq6s',
    appId: '1:11481576355:ios:ab7483cc24701300be6016',
    messagingSenderId: '11481576355',
    projectId: 'lele-wise-5f987',
    databaseURL: 'https://lele-wise-5f987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lele-wise-5f987.appspot.com',
    iosBundleId: 'com.example.lelewiseMobileApps.RunnerTests',
  );
}
